# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "Hugo FixIt Blog"
baseURL = "/"
# theme = "FixIt"
defaultContentLanguage = "en"
languageCode = "en"
hasCJKLanguage = false
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = false
relativeURLs = true
buildDrafts = false
summaryLength = 150
# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
